export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  EXECUTION_CONFLICT: "EXECUTION_CONFLICT",
  INDEXED_DB_UNAVAILABLE: "INDEXED_DB_UNAVAILABLE"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
