export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DMX_ADDRESS_OVERLAP: "DMX_ADDRESS_OVERLAP",
  FIXTURE_DISABLED_IN_SCENE: "FIXTURE_DISABLED_IN_SCENE",
  FIXTURE_NOT_FOUND: "FIXTURE_NOT_FOUND",
  SCENE_NOT_FOUND: "SCENE_NOT_FOUND"
} as const;
